server:
  port:8081
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/userview
      username: root
      password: Ishwarya@90255


    jpa:
      hibernate:
        ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ishwaryakim35@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true